### ISSUE TITLE
Mixtral engine in Triton 

### ISSUE THREAD

**Issue by TallaKuate** [triton-inference-server/tensorrtllm_backend#353]
### System Info

NVIDIA A100 

### Who can help?

@juney-nvidia @nc

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The build command is the following

"python3 /tensorrtllm_backend/tensorrt_llm/examples/llama/build.py --model_dir /Mixtral-8x7B-v0.1/
--use_inflight_batching
--enable_context_fmha
--use_gemm_plugin
--world_size 4
--pp_size 4
--output_dir /engines/4-gpu/"

Here is an error message:

[TRT-LLM] [I] Loading HF LLaMA ... from /Mixtral-8x7B-v0.1/ Traceback (most recent call last): File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 906, in <module> build(0, args) File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 850, in build engine = build_rank_engine(builder, builder_config, engine_name, File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 678, in build_rank_engine hf_llama = hf_model.from_pretrained( AttributeError: 'NoneType' object has no attribute 'from_pretrained'

### Expected behavior

Model engine created

### actual behavior

Error:

hf_llama = hf_model.from_pretrained( AttributeError: 'NoneType' object has no attribute 'from_pretrained'

### additional notes

I am working with tag v0.7.2
Have the set-up running with LLAMA but not with Mixtral.

**Comment by TallaKuate** [comment]
Hey, 
My issue has been resolved with the version v0.8.0. 
Thanks
